from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any


RUNTIME_CONTRACT: dict[str, Any] = {
    "contract_id": "charlesops-runtime-2026-04-29.v2",
    "purpose": "Live gate guard against stale API containers and missing downstream-readiness fields.",
    "required_response_fields": {
        "/api/retrieval/photo-memory-corpus": [
            "retrieval_origin_record_count",
            "retrieval_origin_no_claim_count",
            "next_review_actions",
        ],
        "/api/retrieval/photo-memory-corpus/export.manifest": [
            "retrieval_origin_record_count",
            "retrieval_origin_no_claim_count",
            "next_review_actions",
        ],
        "/api/retrieval/gap-review-slice": [
            "slice_type",
            "review_policy",
            "query",
            "gap_open",
            "completion_signal",
            "items",
            "content_sha256",
        ],
        "/api/retrieval/evidence-corpus": [
            "corpus_type",
            "review_policy",
            "scope",
            "include_unreviewed",
            "record_count",
            "excluded_count",
            "corpus_family_counts",
            "embedding_status_counts",
            "vector_ready_count",
            "ready_for_embedding_count",
            "safety_boundaries",
            "records",
            "excluded",
        ],
        "/api/downstream-readiness/bottlenecks": [
            "queue_type",
            "ordered_area_keys",
            "machine_verification",
            "items",
        ],
        "/api/downstream-readiness/artifact-manifest": [
            "manifest_type",
            "artifact_count",
            "formats",
            "items",
            "content_sha256",
        ],
        "/api/downstream-readiness/artifact-audit": [
            "audit_type",
            "checked_count",
            "mismatch_count",
            "all_hashes_match",
            "checks",
            "content_sha256",
        ],
        "/api/downstream-readiness/morning-handoff": [
            "report_type",
            "headline",
            "primary_bottleneck_area_key",
            "readiness_summary",
            "top_bottlenecks",
            "operator_checklist",
            "retrieval_gap_work",
            "artifact_summary",
            "report_markdown",
            "content_sha256",
        ],
        "/api/context-packs/photo-context-readiness-audit": [
            "audit_type",
            "readiness_status",
            "review_policy",
            "does_not_mutate_state",
            "requires_boundary_clearance",
            "uses_reviewed_photo_context",
            "excludes_system_inference_drafts",
            "completion_signal",
            "machine_draft_profile_count",
            "held_for_adam_review_count",
            "next_review_action_count",
            "next_review_actions",
            "ready_context_pack_asset_count",
            "filename_only_fallback_count",
            "system_inference_leak_count",
            "items",
            "content_sha256",
        ],
        "/api/assets/photo-context-review-pack": [
            "review_policy",
            "manifest",
            "review_worklists",
            "content_sha256",
            "export_preview_yaml",
        ],
        "/api/assets/photo-context-review-pack/session-progress": [
            "progress_type",
            "review_policy",
            "does_not_mutate_state",
            "does_not_create_memory_claim",
            "does_not_create_embedding_record",
            "requires_adam_context",
            "completion_signal",
            "status_counts",
            "blocked_reason_counts",
            "retrieval_gap_missing_field_counts",
            "review_session_task_count",
            "provenance_policy",
            "items",
            "content_sha256",
        ],
        "/api/assets/photo-context-review-pack/session-progress/artifact": [
            "artifact_type",
            "progress_type",
            "review_policy",
            "does_not_mutate_state",
            "does_not_create_memory_claim",
            "does_not_create_embedding_record",
            "requires_adam_context",
            "completion_signal",
            "source_progress_content_sha256",
            "status_counts",
            "review_session_task_count",
            "provenance_policy",
            "items",
            "content_sha256",
        ],
        "/api/assets/photo-context-review-pack/top-context-slice": [
            "slice_type",
            "review_policy",
            "worklist_key",
            "completion_signal",
            "items",
            "content_sha256",
        ],
        "/api/assets/photo-context-review-pack/retrieval-gap-field-worklist": [
            "worklist_type",
            "review_policy",
            "does_not_mutate_state",
            "does_not_create_memory_claim",
            "requires_adam_context",
            "missing_field_counts",
            "field_guidance",
            "items",
            "content_sha256",
            "export_preview_yaml",
            "export_preview_sha256",
        ],
        "/api/assets/photo-context-review-pack/retrieval-gap-payoff-preview": [
            "preview_type",
            "review_policy",
            "does_not_mutate_state",
            "does_not_create_memory_claim",
            "uses_placeholders_for_missing_adam_context",
            "source_worklist_content_sha256",
            "items",
            "content_sha256",
            "export_preview_yaml",
            "export_preview_sha256",
        ],
        "/api/assets/photo-context-review-pack/review-session-plan": [
            "plan_type",
            "review_policy",
            "does_not_mutate_state",
            "source_query",
            "completion_signal",
            "items",
            "content_sha256",
            "export_preview_yaml",
            "export_preview_sha256",
        ],
        "/api/assets/photo-context-review-pack/review-session": [
            "session_type",
            "selection_policy",
            "plan_content_sha256",
            "selected_item_keys",
            "projected_task_delta",
            "items",
        ],
        "/api/assets/photo-review-priority": [
            "summary_type",
            "review_policy",
            "throughput_policy",
            "does_not_mutate_state",
            "does_not_create_memory_claim",
            "no_live_model_call",
            "no_live_embedding_call",
            "completion_signal",
            "items",
            "content_sha256",
            "export_preview_yaml",
            "export_preview_sha256",
        ],
        "/api/prompt-pairs/held-candidates": [
            "review_policy",
            "does_not_promote_to_training_export",
            "requires_adam_gold_edit",
            "worklist_count",
            "worklists",
            "content_sha256",
        ],
        "/api/prompt-pairs/review-progress": [
            "progress_type",
            "review_policy",
            "does_not_mutate_state",
            "does_not_promote_to_training_export",
            "approved_count",
            "candidate_count",
            "blocker_counts",
            "completion_signal",
            "content_sha256",
        ],
        "/api/prompt-pairs/top-blocker-slice": [
            "slice_type",
            "review_policy",
            "selection_policy",
            "requested_blocker",
            "blocker",
            "completion_signal",
            "items",
            "content_sha256",
        ],
        "/api/prompt-pairs/top-blocker-review-session-plan": [
            "plan_type",
            "review_policy",
            "does_not_mutate_state",
            "does_not_promote_to_training_export",
            "selection_policy",
            "requested_blocker",
            "blocker",
            "selected_count",
            "field_plan",
            "items",
            "content_sha256",
            "export_preview_yaml",
            "export_preview_sha256",
        ],
        "/api/prompt-pairs/dpo-rejected-reason-repair-pack": [
            "packet_type",
            "review_policy",
            "blocker",
            "completion_signal",
            "items",
            "content_sha256",
            "export_preview_yaml",
        ],
        "/api/prompt-pairs/dpo-rejected-reason-repair-projection": [
            "projection_type",
            "review_policy",
            "does_not_mutate_task",
            "input_patch",
            "suggested_rejected_issue",
            "before",
            "after",
            "yaml_diff_preview",
            "content_sha256",
        ],
        "/api/prompt-pairs/source-boundary-training-review-pack": [
            "packet_type",
            "review_policy",
            "does_not_mutate_source",
            "does_not_promote_to_training_export",
            "blocker",
            "completion_signal",
            "items",
            "content_sha256",
            "export_preview_yaml",
        ],
        "/api/tasks/{task_id}/pair-generation/preview": [
            "preview_type",
            "review_policy",
            "evidence_policy",
            "does_not_mutate_state",
            "no_live_model_call",
            "prompt_instructions_version",
            "source_task_id",
            "source_title",
            "source_spans_supplied",
            "source_section_count",
            "candidate_pair_count",
            "projected_created_pair_count",
            "projected_held_pair_count",
            "projected_evidence_linked_pair_count",
            "projected_missing_evidence_pair_count",
            "strategy_counts",
            "completion_signal",
            "safety_boundaries",
            "content_sha256",
        ],
        "/api/model-status/demo-generation-request-preview": [
            "preview_type",
            "review_policy",
            "does_not_mutate_state",
            "no_live_model_call",
            "no_generation_created",
            "does_not_promote_to_training_export",
            "api",
            "model_name",
            "reasoning_effort",
            "store",
            "live_generation_blockers",
            "request_count",
            "requests",
            "safety_policy",
            "content_sha256",
            "export_preview_yaml",
            "export_preview_sha256",
        ],
    },
    "no_fine_tuning_api_calls_in_mvp": True,
}


def runtime_contract_payload() -> dict[str, Any]:
    source = Path(__file__).read_bytes()
    return {
        **RUNTIME_CONTRACT,
        "runtime_contract_source_sha256": hashlib.sha256(source).hexdigest(),
    }
