from __future__ import annotations

import io
import json
import math
import random
import re
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence

from sqlmodel import Session, select

from app.config import settings
from app.models import ModelStarterDPOPair, ModelStarterSFTExample, utcnow


PACKAGE_ROOT = "charles-model"
TRAIN_CONFIG = """dataset: "./data/charles_sft.jsonl"
template: "instruction-response"
tokenizer: "auto"
model: "your-base-model-name"
epochs: 3
batch_size: 8
learning_rate: 2e-5
max_seq_len: 4096
save_dir: "./checkpoints/sft"
eval_subset: "val"
logging_steps: 25
"""

DATA_README = """# Charles model starter data

This package is generated by CharlesOps as a trainer-ready starter artifact.

- `charles_sft.jsonl` contains supervised fine-tuning examples.
- `charles_dpo.jsonl` contains preference pairs.
- `charles_sft.train.jsonl` and `charles_sft.val.jsonl` are deterministic split outputs when created.

Every row is newline-delimited UTF-8 JSON. Run `python scripts/check_jsonl.py ...` before training.
"""

PACKAGE_GITIGNORE = """checkpoints/
*.ckpt
*.pt
*.safetensors
__pycache__/
.DS_Store
"""

CHECK_JSONL_SCRIPT = r'''#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List


EMAIL_RE = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.IGNORECASE)
NAME_RE = re.compile(r"\b(?:Charles|Adam|Cathryn|Julia|Michele|Colette|Bernie|Agn[eè]s|Adrienne|Hunter|Noor)\b")


def _text(row: Dict[str, Any], keys: List[str]) -> str:
    return "\n".join(str(row.get(key) or "") for key in keys)


def _issue(issues: List[Dict[str, str]], line: int, severity: str, field: str, code: str, message: str) -> None:
    issues.append({"line": str(line), "severity": severity, "field": field, "code": code, "message": message})


def validate_row(row: Dict[str, Any], line: int, row_type: str, seen: set[str]) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    row_id = str(row.get("id") or "").strip()
    if not row_id:
        _issue(issues, line, "error", "id", "id_missing", "Row id is required.")
    elif row_id in seen:
        _issue(issues, line, "error", "id", "duplicate_id", f"Duplicate id {row_id}.")
    seen.add(row_id)

    if row_type == "sft":
        for field in ["instruction", "response"]:
            if not str(row.get(field) or "").strip():
                _issue(issues, line, "error", field, f"{field}_empty", f"SFT {field} is required.")
        if len(str(row.get("response") or "").strip()) < 40:
            _issue(issues, line, "warning", "response", "response_unusually_short", "Response is unusually short for voice training.")
        pii_tags = row.get("pii_tags")
        text = _text(row, ["instruction", "response", "provenance", "notes"])
        if (EMAIL_RE.search(text) or NAME_RE.search(text)) and not pii_tags:
            _issue(issues, line, "warning", "pii_tags", "pii_tags_empty", "Possible names/emails appear but pii_tags is empty.")
    else:
        for field in ["prompt", "chosen", "rejected"]:
            if not str(row.get(field) or "").strip():
                _issue(issues, line, "error", field, f"{field}_empty", f"DPO {field} is required.")
        chosen = str(row.get("chosen") or "").strip()
        rejected = str(row.get("rejected") or "").strip()
        if chosen and rejected and chosen == rejected:
            _issue(issues, line, "error", "rejected", "chosen_rejected_identical", "Chosen and rejected must be different.")
        if len(chosen) < 40:
            _issue(issues, line, "warning", "chosen", "chosen_unusually_short", "Chosen response is unusually short.")
    return issues


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate Charles model JSONL artifacts.")
    parser.add_argument("path", type=Path)
    parser.add_argument("--type", choices=["sft", "dpo"], required=True)
    args = parser.parse_args()

    issues: List[Dict[str, str]] = []
    seen: set[str] = set()
    checked = 0
    with args.path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            if not raw_line.strip():
                continue
            try:
                row = json.loads(raw_line)
            except json.JSONDecodeError as exc:
                _issue(issues, line_number, "error", "json", "invalid_json", str(exc))
                continue
            if not isinstance(row, dict):
                _issue(issues, line_number, "error", "json", "row_not_object", "Each JSONL row must be an object.")
                continue
            checked += 1
            issues.extend(validate_row(row, line_number, args.type, seen))

    errors = [issue for issue in issues if issue["severity"] == "error"]
    warnings = [issue for issue in issues if issue["severity"] == "warning"]
    print(f"checked={checked} errors={len(errors)} warnings={len(warnings)}")
    for issue in issues:
        print(f"{issue['severity'].upper()} line {issue['line']} {issue['field']} {issue['code']}: {issue['message']}")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

SPLIT_SCRIPT = r'''#!/usr/bin/env python3
from __future__ import annotations

import argparse
import random
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Create deterministic SFT train/validation splits.")
    parser.add_argument("path", type=Path)
    parser.add_argument("--val-ratio", type=float, default=0.05)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    rows = [line for line in args.path.read_text(encoding="utf-8").splitlines() if line.strip()]
    indexed = list(enumerate(rows))
    random.Random(args.seed).shuffle(indexed)
    if len(indexed) <= 1:
        val_count = 0
    else:
        val_count = max(1, min(len(indexed) - 1, round(len(indexed) * args.val_ratio)))
    val_indexes = {index for index, _row in indexed[:val_count]}
    train_rows = [row for index, row in enumerate(rows) if index not in val_indexes]
    val_rows = [row for index, row in enumerate(rows) if index in val_indexes]

    train_path = args.path.with_name(args.path.stem + ".train" + args.path.suffix)
    val_path = args.path.with_name(args.path.stem + ".val" + args.path.suffix)
    train_path.write_text("\n".join(train_rows) + ("\n" if train_rows else ""), encoding="utf-8")
    val_path.write_text("\n".join(val_rows) + ("\n" if val_rows else ""), encoding="utf-8")
    print(f"source={len(rows)} train={len(train_rows)} val={len(val_rows)} seed={args.seed} val_ratio={args.val_ratio}")
    print(f"train={train_path}")
    print(f"val={val_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

PACKAGE_TREE = [
    "charles-model/data/charles_sft.jsonl",
    "charles-model/data/charles_dpo.jsonl",
    "charles-model/data/README.md",
    "charles-model/configs/train_sft.yaml",
    "charles-model/scripts/check_jsonl.py",
    "charles-model/scripts/split_canary_val.py",
    "charles-model/.gitignore",
]


SEED_SFT = [
    {
        "id": "sft-001",
        "instruction": "Write a short note to Adam about seeing a seal in Portland harbor.",
        "response": (
            "I saw a seal.\n"
            "in the harbor, maybe twenty yards off the dock.\n"
            "it surfaced, looked around, then went under.\n"
            "no one else seemed to notice.\n"
            "I stopped.\n\n"
            "love\n"
            "dad"
        ),
        "voice": "father_to_adam",
        "tone": "quiet_observational",
        "provenance": "seeded from CharlesOps starter instructions",
        "consent_status": "family_private_training_ok",
        "pii_tags": ["Adam", "Charles"],
        "notes": "Compact everyday scene with concrete observation and sign-off.",
    },
    {
        "id": "sft-002",
        "instruction": "Explain what makes a good photograph in Charles' voice.",
        "response": (
            "you have to stay with it.\n"
            "most people see the light and go home.\n"
            "but if you wait, sometimes the color changes and the frame arrives.\n"
            "sometimes nothing comes. that's okay too.\n"
            "looking is the whole thing.\n\n"
            "love\n"
            "dad"
        ),
        "voice": "photography_reflection",
        "tone": "reflective",
        "provenance": "seeded from CharlesOps starter instructions",
        "consent_status": "family_private_training_ok",
        "pii_tags": ["Charles"],
        "notes": "Photography principle in voice, not generic advice.",
    },
]

SEED_DPO = [
    {
        "id": "dpo-001",
        "prompt": "How was the soup?",
        "chosen": "soup was thin...\ntasted like nothing\nreminded me of campbell's on a bad day\n\nlove\ndad",
        "rejected": "The soup was bland and unsatisfying. It reminded me of processed food.",
        "provenance": "seeded from CharlesOps starter instructions",
        "why_chosen": "Chosen keeps Charles' terse cadence, concrete aside, ellipses, and family sign-off; rejected is generic summary prose.",
        "notes": "Preference pair demonstrates voice specificity versus generic compression.",
    },
    {
        "id": "dpo-002",
        "prompt": "Tell me about Portland this morning.",
        "chosen": "gray here...\nlight rain\nkeeps the trees happy\nwent for a walk\nocean hiding behind fog\n\nlove\ndad",
        "rejected": "It is rainy and overcast in Portland today, but the weather is good for the local trees.",
        "provenance": "seeded from CharlesOps starter instructions",
        "why_chosen": "Chosen preserves line breaks, restraint, sensory detail, and affectionate close. Rejected explains instead of inhabiting the voice.",
        "notes": "Useful for training away from polished weather-report language.",
    },
]


@dataclass(frozen=True)
class ValidationIssue:
    artifact_type: str
    example_id: str
    field: str
    severity: str
    code: str
    message: str

    def as_dict(self) -> Dict[str, str]:
        return {
            "artifact_type": self.artifact_type,
            "example_id": self.example_id,
            "field": self.field,
            "severity": self.severity,
            "code": self.code,
            "message": self.message,
        }


EMAIL_RE = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.IGNORECASE)
NAME_RE = re.compile(r"\b(?:Charles|Adam|Cathryn|Julia|Michele|Colette|Bernie|Agn[eè]s|Adrienne|Hunter|Noor)\b")


def _non_empty_string(value: Any) -> str:
    return str(value or "").strip()


def _active_sft(session: Session) -> List[ModelStarterSFTExample]:
    return session.exec(
        select(ModelStarterSFTExample)
        .where(ModelStarterSFTExample.status != "deleted")
        .order_by(ModelStarterSFTExample.example_id.asc())
    ).all()


def _active_dpo(session: Session) -> List[ModelStarterDPOPair]:
    return session.exec(
        select(ModelStarterDPOPair)
        .where(ModelStarterDPOPair.status != "deleted")
        .order_by(ModelStarterDPOPair.example_id.asc())
    ).all()


def ensure_seed_data(session: Session) -> None:
    if not session.exec(select(ModelStarterSFTExample)).first():
        for row in SEED_SFT:
            session.add(
                ModelStarterSFTExample(
                    example_id=row["id"],
                    instruction=row["instruction"],
                    response=row["response"],
                    voice=row["voice"],
                    tone=row["tone"],
                    provenance=row["provenance"],
                    consent_status=row["consent_status"],
                    pii_tags=row["pii_tags"],
                    notes=row["notes"],
                )
            )
    if not session.exec(select(ModelStarterDPOPair)).first():
        for row in SEED_DPO:
            session.add(
                ModelStarterDPOPair(
                    example_id=row["id"],
                    prompt=row["prompt"],
                    chosen=row["chosen"],
                    rejected=row["rejected"],
                    provenance=row["provenance"],
                    why_chosen=row["why_chosen"],
                    notes=row["notes"],
                )
            )
    session.commit()


def sft_row(example: ModelStarterSFTExample) -> Dict[str, Any]:
    return {
        "id": example.example_id,
        "instruction": example.instruction,
        "response": example.response,
        "voice": example.voice,
        "tone": example.tone,
        "provenance": example.provenance,
        "consent_status": example.consent_status,
        "pii_tags": example.pii_tags,
        "notes": example.notes,
    }


def dpo_row(pair: ModelStarterDPOPair) -> Dict[str, Any]:
    return {
        "id": pair.example_id,
        "prompt": pair.prompt,
        "chosen": pair.chosen,
        "rejected": pair.rejected,
        "provenance": pair.provenance,
        "why_chosen": pair.why_chosen,
        "notes": pair.notes,
    }


def to_jsonl(rows: Iterable[Dict[str, Any]]) -> str:
    return "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows)


def validate_model_starter(
    sft_examples: Sequence[ModelStarterSFTExample],
    dpo_pairs: Sequence[ModelStarterDPOPair],
) -> Dict[str, Any]:
    issues: List[ValidationIssue] = []
    seen_sft: set[str] = set()
    seen_dpo: set[str] = set()
    for example in sft_examples:
        example_id = example.example_id
        if not _non_empty_string(example_id):
            issues.append(ValidationIssue("sft", example_id, "id", "error", "id_missing", "SFT id is required."))
        elif example_id in seen_sft:
            issues.append(ValidationIssue("sft", example_id, "id", "error", "duplicate_id", "SFT ids must be unique."))
        seen_sft.add(example_id)
        if not _non_empty_string(example.instruction):
            issues.append(ValidationIssue("sft", example_id, "instruction", "error", "instruction_empty", "Instruction is required."))
        if not _non_empty_string(example.response):
            issues.append(ValidationIssue("sft", example_id, "response", "error", "response_empty", "Response is required."))
        elif len(example.response.strip()) < 40:
            issues.append(ValidationIssue("sft", example_id, "response", "warning", "response_unusually_short", "Response is unusually short for voice training."))
        text = "\n".join([example.instruction or "", example.response or "", example.provenance or "", example.notes or ""])
        if (EMAIL_RE.search(text) or NAME_RE.search(text)) and not example.pii_tags:
            issues.append(ValidationIssue("sft", example_id, "pii_tags", "warning", "pii_tags_empty", "Possible names/emails appear but pii_tags is empty."))

    for pair in dpo_pairs:
        example_id = pair.example_id
        if not _non_empty_string(example_id):
            issues.append(ValidationIssue("dpo", example_id, "id", "error", "id_missing", "DPO id is required."))
        elif example_id in seen_dpo:
            issues.append(ValidationIssue("dpo", example_id, "id", "error", "duplicate_id", "DPO ids must be unique."))
        seen_dpo.add(example_id)
        for field, value in [("prompt", pair.prompt), ("chosen", pair.chosen), ("rejected", pair.rejected)]:
            if not _non_empty_string(value):
                issues.append(ValidationIssue("dpo", example_id, field, "error", f"{field}_empty", f"DPO {field} is required."))
        if _non_empty_string(pair.chosen) and pair.chosen.strip() == pair.rejected.strip():
            issues.append(ValidationIssue("dpo", example_id, "rejected", "error", "chosen_rejected_identical", "Chosen and rejected must be different."))
        if _non_empty_string(pair.chosen) and len(pair.chosen.strip()) < 40:
            issues.append(ValidationIssue("dpo", example_id, "chosen", "warning", "chosen_unusually_short", "Chosen response is unusually short."))

    error_count = len([issue for issue in issues if issue.severity == "error"])
    warning_count = len([issue for issue in issues if issue.severity == "warning"])
    return {
        "checked_sft_count": len(sft_examples),
        "checked_dpo_count": len(dpo_pairs),
        "error_count": error_count,
        "warning_count": warning_count,
        "ready": error_count == 0,
        "issues": [issue.as_dict() for issue in issues],
    }


def split_sft_ids(rows: Sequence[Dict[str, Any]], val_ratio: float = 0.05, seed: int = 42) -> Dict[str, Any]:
    bounded_ratio = min(max(val_ratio, 0.0), 0.5)
    indexed = list(enumerate(rows))
    random.Random(seed).shuffle(indexed)
    if len(indexed) <= 1:
        val_count = 0
    else:
        val_count = max(1, min(len(indexed) - 1, math.floor(len(indexed) * bounded_ratio + 0.5)))
    val_indexes = {index for index, _row in indexed[:val_count]}
    train_rows = [row for index, row in enumerate(rows) if index not in val_indexes]
    val_rows = [row for index, row in enumerate(rows) if index in val_indexes]
    return {
        "source_count": len(rows),
        "train_count": len(train_rows),
        "val_count": len(val_rows),
        "train_ids": [str(row["id"]) for row in train_rows],
        "val_ids": [str(row["id"]) for row in val_rows],
        "deterministic_seed": seed,
        "val_ratio": bounded_ratio,
        "train_rows": train_rows,
        "val_rows": val_rows,
    }


def package_bytes(session: Session, *, include_split: bool = False, val_ratio: float = 0.05, seed: int = 42) -> bytes:
    ensure_seed_data(session)
    sft_rows = [sft_row(example) for example in _active_sft(session)]
    dpo_rows = [dpo_row(pair) for pair in _active_dpo(session)]
    split = split_sft_ids(sft_rows, val_ratio=val_ratio, seed=seed)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(f"{PACKAGE_ROOT}/data/charles_sft.jsonl", to_jsonl(sft_rows))
        archive.writestr(f"{PACKAGE_ROOT}/data/charles_dpo.jsonl", to_jsonl(dpo_rows))
        if include_split:
            archive.writestr(f"{PACKAGE_ROOT}/data/charles_sft.train.jsonl", to_jsonl(split["train_rows"]))
            archive.writestr(f"{PACKAGE_ROOT}/data/charles_sft.val.jsonl", to_jsonl(split["val_rows"]))
        archive.writestr(f"{PACKAGE_ROOT}/data/README.md", DATA_README)
        archive.writestr(f"{PACKAGE_ROOT}/configs/train_sft.yaml", TRAIN_CONFIG)
        archive.writestr(f"{PACKAGE_ROOT}/scripts/check_jsonl.py", CHECK_JSONL_SCRIPT + "\n")
        archive.writestr(f"{PACKAGE_ROOT}/scripts/split_canary_val.py", SPLIT_SCRIPT + "\n")
        archive.writestr(f"{PACKAGE_ROOT}/.gitignore", PACKAGE_GITIGNORE)
    return buffer.getvalue()


def write_package_zip(session: Session) -> Path:
    content = package_bytes(session)
    export_dir = Path(settings.storage_root) / "exports"
    export_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = export_dir / f"charles-model-{timestamp}.zip"
    path.write_bytes(content)
    return path


def touch_updated(model: Any) -> None:
    model.updated_at = utcnow()
